name: Hello world workflow
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    hello:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
            - name: Print hello world
              run: echo "Hello world"
              shell: cmd

    goodbye:
        runs-on: windows-latest
        steps:
            - name: goodbye world
              run: echo "bye world"
              shell: cmd
