name: Create a comment on new issues
on:
    issues:
       types: [opened]

jobs:
    comment-on-issue:
        runs-on: windows-latest
        steps: 
            - name: "dump github context"
              run: echo ${{ toJSON(github.event) }}
              shell: cmd